# -*- coding: utf-8 -*-
"""Copy of multiple_linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pR2MqmyQ5UBarpri4fy1_r8ERA5m3Wb3

# Multiple Linear Regression

## Importing the libraries
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer

"""## Importing the dataset"""

startup=pd.read_csv('50_Startups.csv')
X=startup.iloc[:,:-1]
y=startup.iloc[:,-1]

"""## Encoding categorical data"""

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

"""## Splitting the dataset into the Training set and Test set"""

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

"""## Training the Multiple Linear Regression model on the Training set"""

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)

"""## Predicting the Test set results"""

y_new=lr.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_new.reshape(len(y_new),1), y_test.to_numpy().reshape(len(y_test),1)),1))