# -*- coding: utf-8 -*-
"""Copy of simple_linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u-LQcqaz-ug-YivKrrgSVbxUGque-UI1

# Simple Linear Regression

## Importing the libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""## Importing the dataset"""

data=pd.read_csv('Salary_Data.csv')
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

"""## Training the Simple Linear Regression model on the Training set"""

from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(X_train,y_train)

"""## Predicting the Test set results"""

y_pred=LR.predict(X_test)

"""## Visualising the Training set results"""

plt.scatter(X_train,y_train,color='green')
plt.plot(X_train,LR.predict(X_train), color='purple')
plt.title("yes")
plt.xlabel("years of Experience")
plt.ylabel("salary")
plt.show()

"""## Visualising the Test set results"""

plt.scatter(X_test,y_test,color='green')
plt.plot(X_train,LR.predict(X_train), color='purple')
plt.title("yes")
plt.xlabel("years of Experience")
plt.ylabel("salary")
plt.show()