# -*- coding: utf-8 -*-
"""Copy of thompson_sampling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cd_En3Yha9A6RvezpzBVfuP6w4VHkF_t

# Thompson Sampling

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

ads=pd.read_csv('Ads_CTR_Optimisation.csv')

"""# Impelemt Thomson MOdel

"""

import random
N=10000
d=10
i0reward=[0]*d
i1reward=[0]*d
ads_selected=[]
for n in range(0,N):
  ad=0
  max_count=0
  for i in range(0,d):
    random_beta=random.betavariate(i0reward[i]+1,i1reward[i]+1)
    if (random_beta>max_count):
      max_count=random_beta
      ad=i
  ads_selected.append(ad)
  reward=ads.values[n,ad]
  if (reward==1):
    i1reward[ad]+=1
  if (reward==0):
    i0reward[ad]+=1

"""## Visualising the results - Histogram"""

plt.hist(ads_selected)
plt.title('Lawda LELE')
plt.show()