# -*- coding: utf-8 -*-
"""Copy of apriori.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17NBp1pKp5t8Kwcow--WRPvaGlPe-kwDy

# Apriori
"""

!pip install apyori

"""## Importing the libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""## Data Preprocessing"""

mbo=pd.read_csv('Market_Basket_Optimisation.csv', header = None)
transactions=[]
for i in range(1, 7501):
  transactions.append([str(mbo.values[i,j]) for j in range(0,20)])

print(transactions)

"""## Training the Apriori model on the dataset"""

from apyori import apriori
x=apriori(transactions = transactions, min_support = 0.003, min_confidence= 0.2, min_lift= 3, min_lenght=2,max_lenght=2)

"""## Visualising the results

### Displaying the first results coming directly from the output of the apriori function
"""

results=list(x)
results

"""### Putting the results well organised into a Pandas DataFrame"""

def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])

"""### Displaying the results non sorted"""

print(resultsinDataFrame)

"""### Displaying the results sorted by descending lifts"""

resultsinDataFrame.nlargest(n=10, columns='Lift')